export const FETCH_WARUNG_DATA = 'FETCH_WARUNG_DATA';
export const FETCH_WARUNG_DATA_PENDING = 'FETCH_WARUNG_DATA_PENDING';
export const FETCH_WARUNG_DATA_FULLFILED = 'FETCH_WARUNG_DATA_FULLFILED';
export const FETCH_WARUNG_DATA_REJECTED = 'FETCH_WARUNG_DATA_REJECTED';

export const FETCH_MAKANAN_DATA = 'FETCH_MAKANAN_DATA';
export const FETCH_MAKANAN_DATA_PENDING = 'FETCH_MAKANAN_DATA_PENDING';
export const FETCH_MAKANAN_DATA_FULLFILED = 'FETCH_MAKANAN_DATA_FULLFILED';
export const FETCH_MAKANAN_DATA_REJECTED = 'FETCH_MAKANAN_DATA_REJECTED';
