export const NAVIGATION_NAVIGATE = 'Navigation/NAVIGATE';

export const FETCH_DATA_LIST_WARUNG = 'FETCH_DATA_LIST_WARUNG';
export const SELECT_DATA_WARUNG = 'SELECT_DATA_WARUNG';
export const FETCH_DATA_LIST_REVIEW_WARUNG = 'FETCH_DATA_LIST_REVIEW_WARUNG';
export const ERROR_WARUNG = 'ERROR_WARUNG';
export const UPDATE_THIS_USER_REVIEW_WARUNG = 'UPDATE_THIS_USER_REVIEW_WARUNG';
export const FETCH_SEARCHED_LIST_WARUNG = 'FETCH_SEARCHED_LIST_WARUNG';

export const FETCH_DATA_LIST_MAKANAN = 'FETCH_DATA_LIST_MAKANAN';
export const FETCH_DATA_LIST_MAKANAN_BY_SELECTED_WARUNG = 'FETCH_DATA_LIST_MAKANAN_BY_SELECTED_WARUNG';
export const SELECT_DATA_MAKANAN = 'SELECT_DATA_MAKANAN';
export const FETCH_DATA_LIST_REVIEW_MAKANAN = 'FETCH_DATA_LIST_REVIEW_MAKANAN';
export const ERROR_MAKANAN = 'ERROR_MAKANAN';
export const UPDATE_THIS_USER_REVIEW_MAKANAN = 'UPDATE_THIS_USER_REVIEW_MAKANAN';
export const FETCH_SEARCHED_LIST_MAKANAN = 'FETCH_SEARCHED_LIST_MAKANAN';

export const FETCH_DATA_COORDINATE_LOCATION = 'FETCH_DATA_COORDINATE_LOCATION';
export const FETCH_DATA_THIS_USER = 'FETCH_DATA_THIS_USER';
export const ERROR_APP_SETTING = 'ERROR_APP_SETTING';

export const LOGIN_THIS_USER = 'LOGIN_THIS_USER';
export const DAFTAR_THIS_USER = 'DAFTAR_THIS_USER';

export const LOGOUT_THIS_USER = 'LOGOUT_THIS_USER';
