export const NAVIGATION_NAVIGATE = 'Navigation/NAVIGATE';

export const FETCH_WARUNG_DATA_PENDING = 'FETCH_WARUNG_DATA_PENDING';
export const FETCH_WARUNG_DATA_FULLFILED = 'FETCH_WARUNG_DATA_FULLFILED';
export const FETCH_WARUNG_DATA_REJECTED = 'FETCH_WARUNG_DATA_REJECTED';

export const FETCH_MAKANAN_DATA_PENDING = 'FETCH_MAKANAN_DATA_PENDING';
export const FETCH_MAKANAN_DATA_FULLFILED = 'FETCH_MAKANAN_DATA_FULLFILED';
export const FETCH_MAKANAN_DATA_REJECTED = 'FETCH_MAKANAN_DATA_REJECTED';

export const FETCH_LOCATION_FULLFILED = 'FETCH_LOCATION_FULLFILED';
export const FETCH_USER_FULLFILED = 'FETCH_USER_FULLFILED';
